---
- name: Playbook for NFS Server
  hosts: localhost
  become: yes
  vars:
    path: "/data"
  tasks:
    - name: install package
      apt:
        name: nfs-kernel-server
        state: present
    - name: share directory exists
      file:
        path: "{{ path }}"
        state: directory
        mode: 0777
        owner: root
        group: root
    - name: share in /etc/exports file
      lineinfile:
        path: /etc/exports
        state: present
        line: '{{ share }} *(rw,sync,root_squash)'
      notify: restart NFS server 
    - name: export share
      command: "exportfs -rav"
  handlers:
    - name: enable nfs-server service
      systemd:
        name: nfs-kernel-server.service
        state: restarted
        enabled: true

    