---
- name: Playbook for NFS Server
  hosts: localhost
  become: yes
  vars:
    share_path: "/data"
  tasks:
    - name: install package
      apt:
        name: nfs-kernel-server
        state: present
    - name: share directory exists
      file:
        path: "{{ share_path }}"
        state: directory
        mode: 0777
        owner: root
        group: root
    - name: share in /etc/exports file
      lineinfile:
        path: /etc/exports
        state: present
        line: '{{ share_path }} *(rw,sync,root_squash)'
      notify: restart NFS server 
    - name: export share
      command: "exportfs -rav"

  handlers:
    - name: restart NFS server
      systemd:
        name: nfs-server.service
        state: restarted
        enabled: true
